insert into usr (first_name, middle_name, last_name, email) values
('Алексей', 'Игровевич', 'Иванов', 'ivanov@my.example.com'),
('Валерий', 'Петрович', 'Петров', 'valera2@my.example.com'),
('Семен', 'Петрович', 'Сидоров', 'semen33@my.example.com'),
('Семен', 'Семенович', 'Алексеев', 'alekseev44@my.example.com'),
('Леха', 'Вячеславович', 'Валериевич', 'lexa55@my.example.com'),
('Вячеслав', 'Александрович', 'Иванович', 'slava3@my.example.com'),
('Денис', 'Константинович', 'Петрович', 'kuznrtsov232@my.example.com'),
('Влад', 'Иванович', 'Горбатенков', 'gorbanenkov22@my.example.com'),
('Игорь', 'Артемьевич', 'Никандрович', 'bogash132@my.example.com'),
('Петя', 'Семенович', 'Игоревич', 'Petrov5552v@my.example.com');